### ISSUE TITLE
Gatsby image - Lightbox not fired when thumbnails not lazy-loaded yet

### ISSUE THREAD

**Issue by ondrejv** [michelecocuccio/simple-react-lightbox#121] opened 2021-01-24 19:06 UTC
**Describe the bug**
Hi, I'm experiencing an issue when thumbnails within a page are not loaded - are somewhere down the page, e.g. one at top of the page, another one at the bottom. In such case, lightbox doesn't work - thumbnails are not clickable and lightbox is not fired.
You can take a look here: [https://codesandbox.io/s/dreamy-galileo-eobi0](https://codesandbox.io/s/dreamy-galileo-eobi0) ([https://eobi0.sse.codesandbox.io/](https://eobi0.sse.codesandbox.io/))

I was wondering whether it is a matter of the images within links, but the same can be seen when using just pure GatsbyImages:
[https://codesandbox.io/s/dreamy-galileo-eobi0?file=/src/pages/page-2.js](https://codesandbox.io/s/dreamy-galileo-eobi0?file=/src/pages/page-2.js) ([https://eobi0.sse.codesandbox.io/page-2](https://eobi0.sse.codesandbox.io/page-2))

**Environment**
Tested in Chrome, FF, iOS Safari
Clear your browser cache for repeated attempts

Thank you in advance for looking into this.

Cheers

**Comment by ondrejv** [comment] 2021-01-25 09:19
I just tried it without thumbnail images in the lightbox, but to no avail - the misbehavior is the same.

**Comment by michelecocuccio** [comment] 2021-01-25 09:40
@ondrejv hello, thanks for this and for the detailed example on CodeSandbox is very appreciated.

I have identified the issue and I am trying to apply a fix. The problem is due to Gatsby and images that are lazy loaded. This makes impossibile for the document to wait for the images to be fully loaded and it conflicts with the function that I have created to wait until images are loaded in the DOM.

I will do my best to try to fix this but I am not 100% sure. I'll keep you posted.

**Comment by Mites88** [comment] 2021-01-26 02:05
I noticed that too while building my site and AFAIK this is the only lightbox library that works well with Gatsby. Would be a huge deal if this could be fixed.

As a quick workaround you can give each thumb its own wrapper. But you lose navigation funcionality.

**Comment by michelecocuccio** [comment] 2021-01-26 08:39
@Mites88 I understand the frustration, unfortunately this is not entirely up to me but the way lazy loading images works with Gatsby in the DOM. I am trying my best to find a fix.

**Comment by Karlos137** [comment] 2021-01-29 09:18
@michelecocuccio Hello, I'm experiencing the same issue but with Next.js (9.5.2). Switching to an older version of the Lightbox, such as v3.3.4-2, solves the issue for me. But there is another issue with this older version. In Chrome v88, images in the lightbox are displayed with the wrong aspect ratio (the width of the image is lower and image is displayed incorrectly).

**Comment by michelecocuccio** [comment] 2021-01-29 09:24
@Karlos137 hello.

Unfortunately lazy-loaded images and JavaScript Promises don't go along well and also both NextJS and Gatsby do a lot of things with the image itself. I am trying very very HARD to fix the issue but I don't see a way out for now. Don't use older versions as of course they have bugs that have been fixed over the time.

**Comment by Karlos137** [comment] 2021-01-29 09:34
@michelecocuccio Thank you very much. The older version I mentioned worked very well in all browsers till now. Now - but only in Chrome 88 - there is bug with image ratio. Everything else works perfectly for me. Newest version (3.5.5) does not have this image ratio bug in Chrome 88, but does not open at all on click till I scroll down the page to display all images first.

So it looks like there is something in the old versions that fixes this bug.

**Comment by Karlos137** [comment] 2021-01-29 09:48
@michelecocuccio I don't have any bugs in the Safari (14.0.2) btw. Neither on the newest nor the older version of simple-react-lightbox. The image ratio bug in the older versions might be caused by the newly added support of the aspect-ratio property in Chrome 88.

**Comment by Karlos137** [comment] 2021-01-29 09:52
@michelecocuccio Also, this site - https://mobilizujeme.cz/clanky/xiaomi-mi-watch-lite-recenze - is currently using simple-react-lightbox v3.5.5 and next v9.5.2, if you want to test it out.

Thank you.

**Comment by michelecocuccio** [comment] 2021-01-29 11:00
@Karlos137  thanks for this.

I haven't been able to reproduce the image ratio bug. Also could we keep it as a separate issue for now? I think I will keep the focus on this to be the "lazy" loading bug. As I have mentioned I have been working hard but I have my actual job to do so I will try my best to find a way to fix it and let you know my progress.

Thanks a lot :)

**Comment by Karlos137** [comment] 2021-01-29 11:18
@michelecocuccio Yes, of course, thank you very much. 

I also have live site, where you can see the ratio bug and no "lazy" loading bug - https://hoteldolina.eu/galeria/izby-hotel-dolina

It is running on simple-react-lightbox v3.3.3 and gatsby v2.22.15.

Perhaps this information will help to resolve the bug soon.
Thank you

**Comment by michelecocuccio** [comment] 2021-01-29 12:17
@Karlos137 thanks for that.

In regard of the ratio if you want to add a quick fix to make your website work you could override your CSS to remove     "aspect-ratio: auto 533 / 800". The image has a class of `SRLImage` and you can add a class of "width: 100% !important".

**Comment by Karlos137** [comment] 2021-01-29 12:38
@michelecocuccio Thank you, I'll try! :)

**Comment by michelecocuccio** [comment] 2021-02-01 21:19
@ondrejv @Karlos137 

this bug should be now fixed in version 3.6.0. I have tested with Gatsby lazy loaded images and it should work as well with NextJS images. Could you please let me know? Thanks

**Comment by ondrejv** [comment] 2021-02-02 10:00
You nailed it! 3.6.0 and 3.6.1 seems to do the trick: https://eobi0.sse.codesandbox.io/
Awesome!

**Comment by Mites88** [comment] 2021-02-04 15:05
Works flawlessly. Thank you @michelecocuccio!

**Closed** 2021-02-04 17:37 UTC
Labels: bug

**Comment by Karlos137** [comment] 2021-02-16 17:02
Thank you, works great for me now :)
