### ISSUE TITLE
Mixing image and video causes `Cannot read property 'parentElement' of null`

### ISSUE THREAD

**Issue by akira108** [michelecocuccio/simple-react-lightbox#140] opened 2021-03-24 07:01 UTC
**Describe the bug**
Hi, I'm building a gallery that consists of thumbnails of image and video with simple-react-lightbox-pro.
But mixing thumbnail `img` with `a` tag and `img` with `video` tag in same `SRLWrapper` gives me following error:
```
TypeError: Cannot read property 'parentElement' of null
```

**Environment*
NextJS 10.0.3
simple-react-lightbox-pro 1.3.2
React 17.0.0
NodeJS 15.8.0

**To Reproduce**
Compose following html with simple-react-lightbox-pro
```html
<SimpleReactLightbox>
<SRLWrapper>
<div>
    <img src={thumbnailUrl} alt={alt} />
    <video
    srl_video_thumbnail={thumbnailUrl}
    srl_video_caption={alt}
    srl_video_controls="true"
    srl_video_autoplay="true"
    srl_video_muted="true"
    style={{ display: 'none' }}>
        <source src={itemUrl} type="video/mp4" />
    </video>
</div>
 <div>
    <a href={itemUrl2} >
        <img
            className={styles.thumbnail}
            src={thumbnailUrl2}
            alt={alt2}
            srl_gallery_image="true"
        />
    </a>
</div>
</SRLWrapper>
...
</SimpleReactLightbox>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4241658/112268161-e3958f00-8cb9-11eb-8504-0e921b8c02c8.png)

Thanks

**Comment by michelecocuccio** [comment] 2021-03-24 08:44
@akira108  hello.

Thank you for this. I will have a look at the bug tonight and try to add a fix as soon as possible. Many thanks for reporting this.

**Comment by michelecocuccio** [comment] 2021-03-24 21:18
@akira108 hello.

This should be fixed in the version 1.3.3 of the PRO package. Could you upgrade it and let me know if the issue is fixed?
Many thanks

**Comment by akira108** [comment] 2021-03-25 01:48
@michelecocuccio Hello.

I tried 1.3.4 and it is fixed!
I really appreciate your quick handling. And many thanks for making this great library.

**Comment by 7iomka** [comment] 2021-03-27 15:11
@michelecocuccio Hi. Currently only images allowed inside <a> tag for youtube videos? I have my custom layout with self-prepared thumbnail image
It's possible to make work with your plugin?
![image](https://user-images.githubusercontent.com/18473137/112725160-771bc980-8f1f-11eb-95f5-d2767e52945f.png)

**Closed** 2021-03-27 19:12 UTC
Labels: bug
