### ISSUE TITLE
Can't perform a react state update on an unmounted component

### ISSUE THREAD

**Issue by JeffMusgrave** [michelecocuccio/simple-react-lightbox#86] opened 2020-09-05 20:13 UTC
I'm using create-react-app, easy-peasy (a redux + immer state management lib) and SRL. 

Currently I am getting an unmount error. There's a previous issue with the same bug where you mentioned there were no async functions in SRL, but there is one here: https://github.com/michelecocuccio/simple-react-lightbox/blob/d692cf2ebceb9a4fe0ef337716aec7c26f9491c9/src/SRL/SRLLightbox/SRLLightboxGallery/index.js#L222 

I'm not sure that is the problem though.

My site has both page navigation and on-page tabs to change the content displayed. Navigating between pages on its own doesn't cause a problem. However, when I navigate from one on-page tab to another, then change pages, I get an unmount error:
![firefox_YYtubX3Kfp](https://user-images.githubusercontent.com/1578618/92312639-ade4bf00-ef90-11ea-80b5-fa61d3e0275c.png)

relevant code:
my page's useEffect to load and unload content:
![Code_WQ2eV5xnGe](https://user-images.githubusercontent.com/1578618/92312663-d40a5f00-ef90-11ea-8cdb-73a9bf16ba26.png)

state management with easy-peasy:
![Code_qR0RWWJFR7](https://user-images.githubusercontent.com/1578618/92312673-e5ec0200-ef90-11ea-95c2-bc8afa7d16ea.png)

component that loads the gallery:
![Code_GJmywlWvCX](https://user-images.githubusercontent.com/1578618/92312703-3fecc780-ef91-11ea-8f46-cc5dd6f27b87.png)

I have also tried placing the SRL tags outside the logical ```&&```, as well as higher up the component tree, but the result is always the same. When I remove SRL the issue disappears.

**Comment by michelecocuccio** [comment] 2020-09-05 20:31
@JeffMusgrave hello :)

It's a bit difficult to understand what the issue is here. I am pretty confident that the async function is not the issue there as is never called unless you click the button to download the image.

Unfortunately your code seem quite vast so I have no way of reproduce something similar. If will be really helpful if you were able to create a CodeSandbox. Also, that's just a warning. I know the wording "memory leak" but if you don't have any performance issue on your website it shouldn't cause any trouble. Of course I would investigate on this if you are able to provide a working example.

Many thanks

**Comment by JeffMusgrave** [comment] 2020-09-05 23:52
Hey, thanks for offering to take a look. I took some time to try and simplify the code—as a result the site does't look pretty, but it should be much easier to sift through! 

Here it is:
https://codesandbox.io/s/vigorous-cookies-dq8nc

Cheers!

**Comment by pangeaos** [comment] 2020-09-11 07:02
Same error!!!

**Comment by michelecocuccio** [comment] 2020-10-08 17:38
@pangeaos @JeffMusgrave Hello :) 

I have finally found the issue. This will be fixed with the next big release which is going to happen soon. Basically if images are being fetched or loaded, and the user changes page, the lightbox will get the new images (that's correct) but React will keep fetching/loading the other images and try to mount them in the now unmounted component. That was causing the error. I have now used a cleanup effect on the useEffect hook to check if the component is being unmounted and therefore to interrupt any asynchronous action.

Thanks for this 👍

**Closed by michelecocuccio** 2020-10-08 17:38 UTC
Labels: bug

**Comment by JeffMusgrave** [comment] 2020-10-23 20:56
@michelecocuccio hey just wondering what kind of ETA you have on the new update for the free and pro versions? 

Cheers!

**Comment by michelecocuccio** [comment] 2020-10-23 22:49
@JeffMusgrave sorry, I am the only one working on this project and I have to prioritise actual freelance work that gives me some money! I am aiming to release it in around 2 weeks. Just worth mentioning that the issue opened here is not causing any "memory leak" so your application is safe. Of course this will be fixed and will improve the lightbox even more. So sorry for the delay!
