### ISSUE TITLE
Can't see buttons with Preact

### ISSUE THREAD

**Issue by DLevai94** [michelecocuccio/simple-react-lightbox#92] opened 2020-10-01 13:25 UTC
**Describe the bug**
If I add Preact to NextJS project I cannot see the controls of the Lightbox. It looks like it's in the DOM, when selecting the elements, they actually taking up space, but can't see them.

**Environment*
NextJS@latest, simple-react-lightbox@latest, preact@latest & TailwindCSS@latest

_app.js:
```
function MyApp({ Component, pageProps }) {
  return (
    <>
      <DefaultSeo {...seo} />
      <SimpleReactLightbox>
        <Component {...pageProps} />
      </SimpleReactLightbox>
    </>
  );
}
```

Page:
```

return (
    <Layout preview={preview}>
      {router.isFallback ? (
        <p>Töltés…</p>
      ) : (
        <>
          .....
            <SRLWrapper options={lightboxOptions}>
.......
            </SRLWrapper>
.....
```

This is my config:
```
const lightboxOptions = {
  buttons: {
    showDownloadButton: false,
    showThumbnailsButton: false,
  },
  caption: {
    showCaption: false,
  },
  translations: {
    autoplayText: 'Lejátszás',
    closeText: 'Bezárás',
    fullscreenText: 'Teljes képernyő',
    nextText: 'Következő',
    pauseText: 'Szünet',
    previousText: 'Előző',
    zoomOutText: 'Kicsinyítés',
  },
};
```

**To Reproduce**
Create a project with NextJS & Preact

**Screenshots**
![image](https://user-images.githubusercontent.com/15244882/94813013-ca411380-03f7-11eb-9f07-cc9952296530.png)
![image](https://user-images.githubusercontent.com/15244882/94813115-e3e25b00-03f7-11eb-8a14-82a77caa3feb.png)
![image](https://user-images.githubusercontent.com/15244882/94813212-02485680-03f8-11eb-8b43-aec2725b90dd.png)

**Comment by michelecocuccio** [comment] 2020-10-01 13:32
@DLevai94 hello.

Sorry but Simple React Lightbox hasn't been tested with Preact. I have never considered Preact to be honest especially with NextJS. I will see If I can do some testing at some point and see what's the issue.

**Comment by DLevai94** [comment] 2020-10-01 13:36
I'll be pretty sure to contribute and help with this issue, if you have any idea, where should I start looking for it

**Comment by michelecocuccio** [comment] 2020-10-01 13:42
@DLevai94 Unfortunately I have used Preact a long time ago in the past, and I had so many issues that I have never used it again so I don't know what they are stripping out from the latest versions of React. 

If you want to contribuite you can just download the repo and test it with a Preact app instead with a React app? The controls for the lightbox are located [here](https://github.com/michelecocuccio/simple-react-lightbox/tree/master/src/SRL/SRLLightbox/SRLLightboxGallery/SRLLightboxControls) but it's pretty difficult to understand what the issue could be. As I am doing some work on the lightbox in the next few days I can try to reproduce your issue and see if I can find the cause.

Thanks

**Comment by michelecocuccio** [comment] 2020-10-05 12:13
@DLevai94 hello.

I have done some testings with Preact/NextJS. I didn't had any issue with the buttons / icons using your exact settings so I am afraid I don't know what's happening. 

Although I have found another issue due to the incompatibility with Preact and Framer Motion (which is used by Simple React Lightbox). The lightbox was crashing when closing it. Unfortunately is difficult to get at the bottom of the error but I can overcome the issue by adding an option to the settings object called "usingPreact" which you will set to `true` in case you are indeed using Preact. 

Did you had issue closing the lightbox? I know you don't have the button but you could close it by clicking outside of an image. Can you let me know if it was crashing as well when closing it?

Thanks

**Comment by DLevai94** [comment] 2020-10-05 12:15
@michelecocuccio Thanks for checking it out. I've closed it without any issue, by clicking on the overlay or pressing `Esc`

**Comment by michelecocuccio** [comment] 2020-10-05 12:19
@DLevai94 oh gosh!

Sorry to bother you. Can I ask you to link a copy of your package.json? I have used [this](https://github.com/vercel/next.js/tree/canary/examples/using-preact) to test it with Preact/NextJS. And it has the following:

`    "next": "^9.4.0",
    "preact": "^10.4.4",
    "preact-render-to-string": "^5.1.9",
    "react": "github:preact-compat/react#1.0.0",
    "react-dom": "github:preact-compat/react-dom#1.0.0",
`
It's honestly really tricky to tackle this issue :) But if you try using the lightbox with the boilerplate I have linked above, which is using NextJS and Preact, you will see that the icons are showing up.

**Comment by DLevai94** [comment] 2020-10-05 12:25
Sure. Used these packages:

```
dependencies: {
    "next": "latest",
    "preact": "10.4.8",
    "preact-render-to-string": "5.1.10",
    "react": "preact-compat/react#1.x",
    "react-dom": "preact-compat/react-dom#1.x",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.1.1",
.....},
devDependencies: {
    "@prefresh/next": "1.1.0",
    "react-refresh": "0.8.3",
....}
```

With this `next.config.js`:
```
const withPlugins = require('next-compose-plugins');
const withPrefresh = require('@prefresh/next');
const nextImg = require('next-img/plugin');

const plugins = [
  [
    nextImg,
    {
      persistentCache: false,
      jpeg: {
        quality: 70,
        webp: {
          quality: 90,
          reductionEffort: 6,
        },
      },
    },
  ],
  [withPrefresh],
];

const nextConfig = {
  experimental: {
    modern: true,
    polyfillsOptimization: true,
  },

  webpack(config, { dev, isServer }) {
    // Move Preact into the framework chunk instead of duplicating in routes:
    const splitChunks = config.optimization && config.optimization.splitChunks;
    if (splitChunks) {
      const cacheGroups = splitChunks.cacheGroups;
      const test = /[\\/]node_modules[\\/](preact|preact-render-to-string|preact-context-provider)[\\/]/;
      if (cacheGroups.framework) {
        cacheGroups.preact = Object.assign({}, cacheGroups.framework, { test });
        // if you want to merge the 2 small commons+framework chunks:
        // cacheGroups.commons.name = 'framework';
      } else {
        cacheGroups.preact = {
          name: 'commons',
          chunks: 'all',
          test,
        };
      }
    }
    if (isServer) {
      // mark `preact` stuffs as external for server bundle to prevent duplicate copies of preact
      config.externals.push(/^(preact|preact-render-to-string|preact-context-provider)([\\/]|$)/);
      // generate sitemap
      require('./scripts/generate-sitemap');
    }

    // Install webpack aliases:
    const aliases = config.resolve.alias || (config.resolve.alias = {});
    aliases.react = aliases['react-dom'] = 'preact/compat';

    // inject Preact DevTools
    if (dev && !isServer) {
      const entry = config.entry;
      config.entry = () =>
        entry().then((entries) => {
          entries['main.js'] = ['preact/debug'].concat(entries['main.js'] || []);
          return entries;
        });
    }

    return config;
  },
};

module.exports = withPlugins(plugins, nextConfig);
```

Can't link it, because it's a private repo, but here're the 2 files in a gist: https://gist.github.com/DLevai94/3d644d6cdbecc35270e63904c2cb6635

**Comment by michelecocuccio** [comment] 2020-10-05 15:19
@DLevai94 I have done some other tests and still I have issues with Preact when closing the lightbox (which as I mentioned, I have now fixed) so doing some testing with Preact was useful, thanks! 

Unfortunately I don't have a clue why the icons are not showing for you. They are rendered in the document from what I can see so it could be that something else is conflicting with the style, probably the best thing to do is to test thing individually. Maybe try to inspect the CSS and see what's happening. I am not really able to help without actually looking at the code and I can't reproduce the issue.

**Closed by michelecocuccio** 2020-10-05 15:19 UTC
Labels: bug
