### ISSUE TITLE
Quirks on mobile

### ISSUE THREAD

**Issue by cristinabuenahora** [michelecocuccio/simple-react-lightbox#120] opened 2021-01-22 14:26 UTC
**Description**
A couple quirks on mobile. When I expand an image:
- I can still scroll the content in the background. 
- When you pinch and zoom, you lose the x instead of just zooming the image and keeping the x in the right corner. 

**Environment**
Using Node version 12.16.1 and React version 16.13.1 

**To Reproduce**
1. On your phone, go to https://demo.simple-react-lightbox.dev/
2. Click on any image
3. Simulate scroll behavior - you'll notice the content in the background scrolls which is a lil weird. 
4. Pinch to zoom - X disappears and you have to pinch out to get it back

**Comment by michelecocuccio** [comment] 2021-01-22 16:23
@cristinabuenahora hello and thanks for flagging this.

Could I ask you which device are you using? Is it Android or IOS? And which version of Android / IOS? I have tested on android and I can't reproduce the scrolling issue. In regards of the pinch-to-zoom again I couldn't reproduce the behaviour as in my case it only zoom the image. 

I think this could also depend on how you set the `[<meta name="viewport">](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)` in your HTML. If you allow people to pinch to zoom and don't set an initial scale, any website or page that you pinch to zoom in will overflow the device width/height. 

I will do some further testing to check if I can reproduce the behaviour in the meantime.

**Comment by cristinabuenahora** [comment] 2021-01-22 16:39
Hey Michele - I'm using safari on an iPhone x (14.3) and an iPhone 8 (also 14.3).

In the HTML, we have <meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by cristinabuenahora** [comment] 2021-01-28 00:15
Hey Michele - Just following up, have you had a chance to take a look?

**Comment by michelecocuccio** [comment] 2021-01-28 00:27
@cristinabuenahora hello. I have forgot to reply.

The scrolling issue on mobile has been fixed in version 3.5.6. If you update the package you shouldn't have the issue anymore. In regards of the pinch to zoom at the moment is just behaving like a normal page on mobile, so it's scaling the page up. There is no particular functionality related to the pinch to zoom unless you tap on the picture first and then you can use pan zoom to scale it up and down. I am already working to improve this in the next release to have a more UX friendly experience. 

Thanks

**Closed by michelecocuccio** 2021-01-28 00:27 UTC
Labels: bug

**Comment by cristinabuenahora** [comment] 2021-01-28 00:28
Sounds good! Thanks Michele. Appreciate your help.
