### ISSUE TITLE
Doesn't work with gatsby-image when using the Gallery approach

### ISSUE THREAD

**Issue by ds-codemag** [michelecocuccio/simple-react-lightbox#11] opened 2020-01-22 18:37 UTC
As in title. It doesn't work with gatsby-image e.g <Img fluid={src} /> gatsby creates something like:

```
<div class=" gatsby-image-wrapper" style="position: relative; overflow: hidden;">
    <div style="width: 100%; padding-bottom: 66.5625%;"></div>
    <img src="data:image/jpeg;base64..." alt="" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 0; transition-delay: 500ms;" id="element0">
    <picture>
        <source srcset="srcset" sizes="(max-width: 350px) 100vw, 350px">
        <img sizes="(max-width: 350px) 100vw, 350px" srcset="srcset" src="src" alt="Zdjęcie" loading="lazy" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;">
    </picture>
    <noscript>
        <picture>
            <source srcset="" sizes="(max-width: 350px) 100vw, 350px" /><img loading="lazy" sizes="(max-width: 350px) 100vw, 350px" srcset="srcset" src="src" alt="Zdjęcie" style="position:absolute;top:0;left:0;opacity:1;width:100%;height:100%;object-fit:cover;object-position:center"/>
        </picture>
    </noscript>
</div>
```

And i get warning:
"HEY!. You have 10 links and 20 images. You likely forgot to add the data-attribute="SRL" to one of your link wrapping your image!"

And error: 
"Cannot read property 'alt' of undefined"

When I don't use gatsby-image component only img html tag everything works fine.

**Comment by michelecocuccio** [comment] 2020-01-23 10:05
Hello, thanks @ds-codemag . 
Yeah the Gatsby image structure is pretty complex so is not supported at the moment. They have two images and also in base64 so I will need to see if there is a way I can support this.

I will see what I can do, is not a "bug" per se but I will consider implementing this as well.

Thanks

**Comment by michelecocuccio** [comment] 2020-01-23 10:49
@ds-codemag Regarding the error:
"Cannot read property 'alt' of undefined"
can you update it to the last version as I have fixed a bug yesterday in case an alt tag wasn't provided

Thanks

**Comment by daiky00** [comment] 2020-06-19 06:38
@michelecocuccio is this support it yet?

**Comment by michelecocuccio** [comment] 2020-06-19 08:33
@daiky00 Gatsby images are now supported yes. Give it a try :)

**Comment by daiky00** [comment] 2020-06-19 14:34
Is there an example that I can follow or any documentation?

**Comment by daiky00** [comment] 2020-06-20 02:52
@michelecocuccio Thats really nice thank you so much :)

**Comment by milianriedel** [comment] 2020-08-08 12:32
@michelecocuccio But image in lightbox is small with width 300px and height 300px, right? How I add bigger image for lightbox? If I query image one more time (fluid this time with maxWidth: 1000px for example) and wrap <Image /> with link with this fluid image in href and add data-attribute="SRL", then is showing only thumbnail and lightbox is stucked with "Loading…". Is there a possibility to make it work this way?

**Comment by michelecocuccio** [comment] 2020-08-08 15:36
@milianriedel I don't fully understand what you mean. You define the size of your Gatsby image based on the image itself. Can you provide a demo on CodeSandbox or similar so I can understand what you mean?

**Comment by azaandam** [comment] 2020-08-11 21:46
I'm having a similar issue as @milianriedel, only I'm using an array of images. Basically I use gatsby-image to display the thumbnail images in the gallery, and for the lightbox I pass the full-size image URL's as href to the anchor tags with the
`data-attribute="SRL"` attribute. But somhow the full size image URL isn't getting passed to the lightbox image to populate the source (SRLImage `src="Loading..."`). Here's my code

gallery-section.js
```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby'
import SimpleReactLightbox, { SRLWrapper } from 'simple-react-lightbox'
import GalleryImage from './gallery-image';

export default () => {
    const data = useStaticQuery(graphql`{
      gallery {
        altText
        sourceUrl
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }`)

    const gallery = data.gallery;

    const options = {
        settings: {
            overlayColor: '#000000',
            autoplaySpeed: 1500,
            transitionSpeed: 900,
            disableKeyboardControls: false,
            disablePanzoom: true,
        },
        buttons: {
            backgroundColor: "#9C2128",
            iconColor: "#FFFFFF",
            showAutoplayButton: false,
            showDownloadButton: false,
            showFullscreenButton: false,
            showThumbnailsButton: false,
        },
        caption: {
            showCaption: false,
        },
        thumbnails: {
            showThumbnails: false,
        },
    };

    return (
        <SimpleReactLightbox>
            <SRLWrapper options={options}>
                {gallery.map((image, i) => 
                    <GalleryImage key={i} {...image} />)
                }
            </SRLWrapper>
        </SimpleReactLightbox>
    )
}
```

gallery-image.js
```
import React from 'react'
import styled from 'styled-components'
import Img from 'gatsby-image'

const GalleryLink = styled.a`
    width: 300px;
    align-items:stretch;
    display:flex;
    margin-right:15px;
    margin-bottom:15px;
`;

const GalleryImage = styled(Img)`
    width: 300px;
    cursor: pointer;
    height:calc( calc( 300px / 2 ) + 60px);
`;

export default ({ childImageSharp, altText, sourceUrl }) =>
    <GalleryLink data-attribute="SRL" href={sourceUrl}>
        <GalleryImage fluid={childImageSharp.fluid} alt={altText} />
    </GalleryLink>
```

**Comment by michelecocuccio** [comment] 2020-08-12 06:31
@azaandam I think the problem is using it with Gatsby image as a thumbnail. I will do some testing and try to reproduce the issue myself. Thanks

**Comment by milianriedel** [comment] 2020-08-12 07:34
@michelecocuccio Sorry, for delay. Yes, I have same problem as @azaandam. I tried to create gallery with thumbnails with gatsby-image and for lightbox with full size Image (image.publicURL for link with data-attribute="SRL"). Also there is now to show just one image thumbnail of gallery (rest hidden) and in lightbox load all of them. I tried it with css show only one thumbnail, but it broke the component.

**Comment by michelecocuccio** [comment] 2020-08-16 16:51
@milianriedel @ds-codemag this should be fixed in version 3.3.0 and above.
Please make sure to update to the latest version.

**Closed by michelecocuccio** 2020-08-16 16:51 UTC

**Comment by azaandam** [comment] 2020-08-17 20:16
Thanks @michelecocuccio for the quick fix. The update works perfectly.

**Comment by michelecocuccio** [comment] 2020-08-17 20:18
@azaandam I am very happy to hear that. I haven't fully tested with Gatsby images but this should cover most of the cases. Gatsby image really has a complex structure in terms of creating the image. Let me know if you encounter any other issue.
